name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Setting environment
        uses: ./.github/actions/setup-environment
      - name: Compile the project
        run: |
          source /opt/ros/noetic/setup.bash
          cargo build
      - name: Run the tests
        run: |
          source /opt/ros/noetic/setup.bash
          ./ci_test.sh
